// <auto-generated />
namespace LivecountStats.DataLayer
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddingViewCounter : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddingViewCounter));
        
        string IMigrationMetadata.Id
        {
            get { return "201711120509485_AddingViewCounter"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
